# Site settings
title: Mozilla Kolkata Blog
email: mozillakolkata@gmail.com
description: "This is the official blog of Mozilla Kolkata Community "
author: "Kumar Anirudha <anirudhastark@yahoo.com> [anistark]"
baseurl: "/blog"
paginate:	5
paginate_path: "page:num"
url: "http://mozillakolkata.github.io/blog/"
twitter_username: mozillakolkata
github_username:  mozillakolkata

# Build settings
markdown: kramdown
permalink: pretty
